name: Build and deploy to Cloudflare

on:
  push:
    branches:
      - main
  repository_dispatch:

jobs:
  build:
    name: Build Next and deploy to Cloudflare
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: EXPORT=1 npm run build
      - name: Deploy to Cloudflare
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          environment: preview
          command: pages deploy out --project-name=all-aboard
    
      